baseURL = 'https://pxp9.github.io/'
languageCode = 'en-us'
title = 'The Software Engineer Oasis'
theme = 'digitalgarden'
enableEmoji = true
relativeURLs = true
googleAnalytics = "UA-PROPERTY_ID"


[Params]
  AuthorName = 'Pepe Márquez Romero'
  GitHubUser = 'pxp9'
  categories = ["rust"]
  description = "I am Pepe Márquez Romero a computer science student."
  images = ['/pxp9_logo.jpg']

[Params.newsletter]
  title = "Subscribe to my blog"
  description = "A curated weekly digest once a week to your mailbox"
  path = "https://www.getrevue.co/profile/username/add_subscriber"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3

[[menu.main]]
  name = 'About'
  url = '/about/about'
  weight = 2

[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 4

[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/_PXP9_'
  weight = 3
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/pxp9'
  weight = 2
#[[menu.social]]
 # name = 'LinkedIn'
  #url = 'https://linkedin.com'
  #weight = 4
[[menu.social]]
  name = 'Email'
  url = 'mailto:pepe.marquezromero@gmail.com'
  weight = 1
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 5


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
